// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uabsjhrxxvkuwmmwaumg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhYnNqaHJ4eHZrdXdtbXdhdW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MzM1ODYsImV4cCI6MjA3MzMwOTU4Nn0.YlOMLFWuUOCj6ThIHqf631B0i6tGcCfrsnqzlgMnWXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});